server:
  port: 6969
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://benuqjksplmzto:fd6779c7b6e89d8b2b6a8b045bcab87a4945089e44cd77cb006cf78d6bd3b5b8@ec2-3-233-7-12.compute-1.amazonaws.com:5432/d1bhq8ouiil57d
    username: benuqjksplmzto
    password: fd6779c7b6e89d8b2b6a8b045bcab87a4945089e44cd77cb006cf78d6bd3b5b8
jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  hibernate:
    ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / BackEnd